# Display.
title: "Merely Useful"
editor: "Greg Wilson"
copyrightyear: "2019"
repo: "https://github.com/merely-useful/merely-useful.github.io"
website: "https://merely-useful.github.io/"
email: "gvwilson@third-bit.com"
organization: https://github.com/merely-useful/
isbn: "000-0-0000000-0-0"

# Order for table of contents.
toc:
  lessons:
  - intro
  bib:
  - bib
  extras:
  - license
  - conduct
  - citation
  - contributing
