# Display.
title: "Merely Useful"
editor: "Greg Wilson"
copyrightyear: "2019"
repo: "https://github.com/merely-useful/merely-useful.github.io"
website: "https://merely-useful.github.io/"
email: "gvwilson@third-bit.com"
organization: https://github.com/merely-useful/
isbn: "000-0-0000000-0-0"

# Order for table of contents.
toc:
  lessons:
  - intro
  bib:
  - bib
  extras:
  - license
  - conduct
  - citation
  - contributing

# Contributors.
people:
  aruliah-dhavide:
    name: "Dhavide Aruliah"
    site: "https://dhavide.github.io/"
    github: "dhavide"
    orcid: "0000-0002-6432-2709"
  bonsma-fisher-madeleine:
    name: "Madeleine Bonsma-Fisher"
    site: "http://madeleinebonsma.com/"
    github: "mbonsma"
    orcid: "0000-0002-5813-4664"
  dursi-jonathan:
    name: "Jonathan Dursi"
    site: "https://www.dursi.ca/"
    github: "ljdursi"
    orcid: "0000-0002-4697-798X"
  fournier-auriel:
    name: "Auriel Fournier"
    site: "http://aurielfournier.github.io/"
    github: "aurielfournier"
    orcid: "0000-0002-8530-9968"
  hertweck-kate:
    name: "Kate Hertweck"
    site: "https://www.linkedin.com/in/katehertweck/"
    github: "k8hertweck"
    orcid: "0000-0002-4026-4612"
  huff-katy:
    name: "Katy Huff"
    site: "http://katyhuff.github.io/"
    github: "katyhuff"
    orcid: "0000-0002-7075-6802"
  irving-damien:
    name: "Damien Irving"
    site: "https://drclimate.wordpress.com/"
    github: "DamienIrving"
    orcid: "0000-0003-1258-5002"
  johnston-luke:
    name: "Luke Johnston"
    site: "http://lukewjohnston.com/"
    github: "lwjohnst86"
    orcid: "0000-0003-4169-2616"
  koch-christina:
    name: "Christina Koch"
    site: "http://christinalk.github.io/"
    github: "christinalk"
    orcid: "0000-0001-8600-8158"
  marshall-brandeis:
    name: "Brandeis Marshall"
    site: "https://www.brandeismarshall.com/"
    github: "brandeism"
    orcid: "0000-0002-6646-8269"
  ostblom-joel:
    name: "Joel Ostblom"
    site: "http://joelostblom.com/"
    github: "joelostblom"
    orcid: "0000-0003-0051-3239"
  turk-matt:
    name: "Matt Turk"
    site: "https://sites.google.com/site/matthewturk/"
    github: "MatthewTurk"
    orcid: "0000-0002-5294-0198"
  wickes-elizabeth:
    name: "Elizabeth Wickes"
    site: "https://elizabethwickes.com/"
    github: "elliewix"
    orcid: "0000-0002-5294-0198"
  wickham-charlotte:
    name: "Charlotte Wickham"
    site: "https://www.cwick.co.nz/"
    github: "cwickham"
    orcid: "0000-0002-6365-5499"
  wilson-greg:
    name: "Greg Wilson"
    site: "http://third-bit.com/"
    github: "gvwilson"
    orcid: "0000-0001-8659-8979"
